/** Reproducible original reference-guided UAV asset; no manufacturer CAD. Node >=22.15. */
import {registerHooks} from 'node:module';
import {writeFileSync,mkdirSync} from 'node:fs';
registerHooks({resolve(s,c,n){return n(s==='three'?new URL('../assets/vendor/three/three.module.js',import.meta.url).href:s,c);}});
const {createResearchDrone}=await import('./drone-geometry.mjs');
const {mergeVertices}=await import('../assets/vendor/three/BufferGeometryUtils.js');
const sharp=(await import('sharp')).default;
const chunks=[];let byteLength=0;const gltf={asset:{version:'2.0',generator:'Johnny reference-guided research UAV authoring pipeline v5'},scene:0,scenes:[{nodes:[]}],nodes:[],meshes:[],materials:[],accessors:[],bufferViews:[],buffers:[{byteLength:0}],images:[],textures:[],samplers:[{magFilter:9729,minFilter:9987,wrapS:10497,wrapT:10497}]};
function buffer(data,target){const pad=(4-byteLength%4)%4;if(pad){chunks.push(Buffer.alloc(pad));byteLength+=pad;}const b=Buffer.from(data.buffer??data,data.byteOffset??0,data.byteLength??data.length),id=gltf.bufferViews.length;gltf.bufferViews.push({buffer:0,byteOffset:byteLength,byteLength:b.length,...(target?{target}:{})});chunks.push(b);byteLength+=b.length;return id;}
const size=256,rgba=Buffer.alloc(size*size*4),normal=Buffer.alloc(size*size*4),rough=Buffer.alloc(size*size*4);
for(let y=0;y<size;y++)for(let x=0;x<size;x++){
 const i=(y*size+x)*4,vertical=(Math.floor(x/8)+Math.floor(y/8))%2,thread=vertical?x%8:y%8;
 const v=Math.round(94+Math.sin(thread/7*Math.PI)*42+Math.sin((vertical?y:x)*Math.PI)*2);
 rgba.set([v,v+2,v+3,255],i);const slope=Math.cos(thread/7*Math.PI)*14;normal.set([vertical?128+slope:128,vertical?128:128+slope,254,255],i);rough.set([255,170+thread*3,255,255],i);
}
for(const raw of [rgba,normal,rough]){const png=await sharp(raw,{raw:{width:size,height:size,channels:4}}).png().toBuffer();const ix=gltf.images.length;gltf.images.push({bufferView:buffer(png),mimeType:'image/png'});gltf.textures.push({source:ix,sampler:0});}
const matMap=new Map();function material(m){if(matMap.has(m))return matMap.get(m);const p={baseColorFactor:[m.color.r,m.color.g,m.color.b,m.opacity],metallicFactor:m.metalness??0,roughnessFactor:m.roughness??1};const def={name:`${m.type}-${m.color.getHexString()}`,pbrMetallicRoughness:p};if(m.isMeshPhysicalMaterial&&m.roughness===.48){p.baseColorFactor=[.30,.32,.34,1];p.baseColorTexture={index:0};p.metallicRoughnessTexture={index:2};def.normalTexture={index:1,scale:.16};p.roughnessFactor=.68;p.metallicFactor=.15;}
if(m.isMeshPhysicalMaterial&&m.clearcoat>0){def.extensions={KHR_materials_clearcoat:{clearcoatFactor:m.clearcoat,clearcoatRoughnessFactor:.08}};gltf.extensionsUsed=['KHR_materials_clearcoat'];}
if(m.emissive&&m.emissive.getHex()){def.emissiveFactor=m.emissive.toArray();}if(m.transparent){def.alphaMode='BLEND';}if(m.side===2)def.doubleSided=true;
const id=gltf.materials.length;gltf.materials.push(def);matMap.set(m,id);return id;}
let vertices=0,triangles=0;function mesh(o){const g=mergeVertices(o.geometry,1e-5),attrs={};for(const [key,semantic] of [['position','POSITION'],['normal','NORMAL'],['uv','TEXCOORD_0']]){const a=g.getAttribute(key);if(!a)continue;if(key==='uv'&&o.material.isMeshPhysicalMaterial&&o.material.roughness===.48){for(let i=0;i<a.array.length;i++)a.array[i]*=8;}const ac={bufferView:buffer(a.array,34962),componentType:5126,count:a.count,type:a.itemSize===3?'VEC3':'VEC2'};if(key==='position'){g.computeBoundingBox();ac.min=g.boundingBox.min.toArray();ac.max=g.boundingBox.max.toArray();vertices+=a.count;}attrs[semantic]=gltf.accessors.length;gltf.accessors.push(ac);}
const p={attributes:attrs,material:material(o.material)};if(g.index){p.indices=gltf.accessors.length;gltf.accessors.push({bufferView:buffer(g.index.array,34963),componentType:g.index.array.BYTES_PER_ELEMENT===2?5123:5125,count:g.index.count,type:'SCALAR'});triangles+=g.index.count/3;}else triangles+=g.getAttribute('position').count/3;const id=gltf.meshes.length;gltf.meshes.push({primitives:[p]});g.dispose();return id;}
function node(o,name){const id=gltf.nodes.length,d={name:name||o.name||'part'};gltf.nodes.push(d);if(o.position.lengthSq())d.translation=o.position.toArray();if(o.quaternion.x||o.quaternion.y||o.quaternion.z)d.rotation=o.quaternion.toArray();if(o.isMesh)d.mesh=mesh(o);if(o.children.length)d.children=o.children.map(c=>node(c));return id;}
const high=createResearchDrone(true),low=createResearchDrone(false);gltf.scenes[0].nodes.push(node(high.root.children[0],'body-near'));gltf.scenes[0].nodes.push(node(low.root.children[0],'body-far'));for(let i=1;i<5;i++)gltf.scenes[0].nodes.push(node(high.root.children[i],`rotor-${i-1}`));
gltf.buffers[0].byteLength=byteLength;let json=Buffer.from(JSON.stringify(gltf));json=Buffer.concat([json,Buffer.alloc((4-json.length%4)%4,32)]);let bin=Buffer.concat(chunks);bin=Buffer.concat([bin,Buffer.alloc((4-bin.length%4)%4)]);const header=Buffer.alloc(12),jh=Buffer.alloc(8),bh=Buffer.alloc(8);header.writeUInt32LE(0x46546c67);header.writeUInt32LE(2,4);header.writeUInt32LE(28+json.length+bin.length,8);jh.writeUInt32LE(json.length);jh.writeUInt32LE(0x4e4f534a,4);bh.writeUInt32LE(bin.length);bh.writeUInt32LE(0x004e4942,4);
mkdirSync('assets/hero-3d/drone',{recursive:true});writeFileSync('assets/hero-3d/drone/research-quad.glb',Buffer.concat([header,jh,json,bh,bin]));const report={vertices,triangles,bufferBytes:byteLength,glbBytes:28+json.length+bin.length,textureGpuBytes:3*size*size*4*4/3,notes:'Geometry and textures shared by all 5 drones. Near/far geometry both resident. Browser overhead excluded.'};writeFileSync('assets/hero-3d/drone/asset-stats.json',JSON.stringify(report,null,2)+'\n');console.log(report);
